# Generated by Django 6.1.1 on 2026-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateField(),
        ),
    ]
