# Generated by Django 6.1.1 on 2026-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_announcement_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='urgent',
        ),
        migrations.AddField(
            model_name='announcement',
            name='banner_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='banner_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='banner_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
