# Generated by Django 6.1.1 on 2026-09-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_announcement_urgent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='floor_map/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
