# Generated by Django 6.1.1 on 2026-09-13 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_floormap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせ'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'エリア', 'verbose_name_plural': 'エリア'},
        ),
        migrations.AlterModelOptions(
            name='calendarnote',
            options={'verbose_name': 'カレンダーメモ', 'verbose_name_plural': 'カレンダーメモ'},
        ),
        migrations.AlterModelOptions(
            name='floormap',
            options={'verbose_name': 'フロアマップ', 'verbose_name_plural': 'フロアマップ'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'スペース', 'verbose_name_plural': 'スペース'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='banner_enabled',
            field=models.BooleanField(default=False, verbose_name='緊急バナー表示'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='banner_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='バナー表示終了日'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='banner_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='バナー表示開始日'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('お知らせ', 'お知らせ'), ('メンテナンス', 'メンテナンス'), ('イベント', 'イベント'), ('運用変更', '運用変更')], max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateField(verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='area',
            name='floor',
            field=models.CharField(max_length=50, verbose_name='フロア'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='date',
            field=models.DateField(unique=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='祝日名'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='image',
            field=models.FileField(upload_to='floor_map/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(max_length=200, verbose_name='利用目的'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.space', verbose_name='スペース'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('upcoming', '予約中'), ('active', '利用中'), ('ended', '利用済み'), ('cancelled', 'キャンセル')], default='upcoming', max_length=10, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='予約者'),
        ),
        migrations.AlterField(
            model_name='space',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='core.area', verbose_name='エリア'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='space',
            name='status',
            field=models.CharField(choices=[('available', '空き'), ('in_use', '使用中'), ('reserved', '予約済み'), ('closed', '停止中')], default='available', max_length=10, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='space',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Django管理サイトへのアクセス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', '一般メンバー'), ('admin', '管理者')], default='member', max_length=10, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', '在籍中'), ('inactive', '退職')], default='active', max_length=10, verbose_name='状態'),
        ),
    ]
