# Generated by Django 6.1.1 on 2026-09-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_announcement_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '作成'), ('updated', '編集'), ('cancelled', 'キャンセル')], max_length=10, verbose_name='操作種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.reservation', verbose_name='予約')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '予約変更履歴',
                'verbose_name_plural': '予約変更履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
