# Generated by Django 6.1.1 on 2026-09-15 21:28

from django.db import migrations, models


def copy_status_to_is_closed(apps, schema_editor):
    Space = apps.get_model('core', 'Space')
    Space.objects.filter(status='closed').update(is_closed=True)


def copy_is_closed_to_status(apps, schema_editor):
    Space = apps.get_model('core', 'Space')
    Space.objects.filter(is_closed=True).update(status='closed')
    Space.objects.filter(is_closed=False).update(status='available')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reservationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='利用停止中'),
        ),
        migrations.RunPython(copy_status_to_is_closed, copy_is_closed_to_status),
        migrations.RemoveField(
            model_name='space',
            name='status',
        ),
    ]
