# Generated by Django 6.1.1 on 2026-09-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_space_status_space_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '予約変更履歴', 'verbose_name_plural': '予約変更履歴'},
        ),
    ]
