# Generated by Django 6.1.1 on 2026-09-15 22:24

from django.db import migrations, models


def copy_status_to_is_cancelled(apps, schema_editor):
    Reservation = apps.get_model('core', 'Reservation')
    Reservation.objects.filter(status='cancelled').update(is_cancelled=True)


def copy_is_cancelled_to_status(apps, schema_editor):
    Reservation = apps.get_model('core', 'Reservation')
    Reservation.objects.filter(is_cancelled=True).update(status='cancelled')
    Reservation.objects.filter(is_cancelled=False).update(status='upcoming')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reservationhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='キャンセル済み'),
        ),
        migrations.RunPython(copy_status_to_is_cancelled, copy_is_cancelled_to_status),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
